# Generated by Django 6.0.1 on 2026-01-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roblox_cores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobloxProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('robux', 'Robux'), ('item', 'Item')], db_column='type', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roblox_products',
            },
        ),
        migrations.CreateModel(
            name='RobuxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Robux Categories',
                'db_table': 'roblox_robux_categories',
            },
        ),
        migrations.CreateModel(
            name='RobloxItem',
            fields=[
                ('robloxproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogues.robloxproduct')),
                ('roblox_item_id_external', models.BigIntegerField(help_text='ID Item dari API Roblox')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('server', models.ForeignKey(db_column='roblox_server_id', on_delete=django.db.models.deletion.CASCADE, to='roblox_cores.robloxserver')),
            ],
            options={
                'db_table': 'roblox_items',
            },
            bases=('catalogues.robloxproduct',),
        ),
        migrations.CreateModel(
            name='RobloxRobux',
            fields=[
                ('robloxproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogues.robloxproduct')),
                ('robux_amount', models.BigIntegerField()),
                ('category', models.ForeignKey(db_column='roblox_robux_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robux_packages', to='catalogues.robuxcategory')),
            ],
            options={
                'verbose_name_plural': 'Robux Packages',
                'db_table': 'roblox_robuxs',
            },
            bases=('catalogues.robloxproduct',),
        ),
    ]
