# Generated by Django 6.0.1 on 2026-01-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robloxitem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/roblox_items/'),
        ),
    ]
