# Generated by Django 6.0.1 on 2026-01-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_alter_robloxitem_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robloxitem',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='robloxproduct',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='robloxrobux',
            options={'verbose_name_plural': 'Robux'},
        ),
    ]
