# Generated by Django 6.0.1 on 2026-01-13 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobloxServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_id', models.BigIntegerField(help_text='ID Server/Game dari Roblox', unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Roblox Server',
                'verbose_name_plural': 'Roblox Servers',
                'db_table': 'roblox_servers',
            },
        ),
        migrations.CreateModel(
            name='RobloxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roblox_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='roblox_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roblox Account',
                'verbose_name_plural': 'Roblox Accounts',
                'db_table': 'roblox_accounts',
                'indexes': [models.Index(fields=['roblox_user_id'], name='roblox_acco_roblox__167671_idx'), models.Index(fields=['username'], name='roblox_acco_usernam_512634_idx')],
            },
        ),
    ]
