# Generated by Django 6.0.1 on 2026-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblox_cores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robloxserver',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
