# Generated by Django 6.0.1 on 2026-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblox_cores', '0002_robloxserver_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robloxserver',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/roblox_sever/'),
        ),
    ]
