# Generated by Django 6.0.1 on 2026-01-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0003_alter_robloxitem_options_alter_robloxproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('sub_total', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction Cart',
                'verbose_name_plural': 'Transaction Carts',
                'db_table': 'transaction_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bank', 'Bank'), ('e_wallet', 'E-Wallet')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Payment',
                'verbose_name_plural': 'Transaction Payments',
                'db_table': 'transaction_payments',
            },
        ),
        migrations.CreateModel(
            name='TransactionCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='roblox_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalogues.robloxproduct')),
                ('transaction_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transactioncart')),
            ],
            options={
                'verbose_name': 'Transaction Cart Item',
                'verbose_name_plural': 'Transaction Cart Items',
                'db_table': 'transaction_cart_items',
            },
        ),
        migrations.CreateModel(
            name='TransactionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('roblox_account_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField(unique=True)),
                ('status', models.CharField(max_length=20)),
                ('sub_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='transactions.transactionpayment')),
            ],
            options={
                'verbose_name': 'Transaction Receipt',
                'verbose_name_plural': 'Transaction Receipts',
                'db_table': 'transaction_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='transactions.transactionreceipt')),
            ],
            options={
                'verbose_name': 'Transaction Item',
                'verbose_name_plural': 'Transaction Items',
                'db_table': 'transaction_items',
            },
        ),
    ]
