# Generated by Django 6.0.1 on 2026-01-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_alter_robloxitem_options_alter_robloxproduct_options_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(db_column='roblox_product_id', default=23, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='catalogues.robloxproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='assets/icons/payment_method/'),
        ),
    ]
