# Generated by Django 6.0.1 on 2026-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='price_at_purchase',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product_name_snapshot',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
