# Generated by Django 6.0.1 on 2026-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_badge_icon_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/users_avatar/'),
        ),
    ]
